name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - uses: actions/checkout@v3
      name: Check out code

    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
    - name: Build Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/image-search-api:latest

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/image-search-api
        tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/image-search-api:latest
