name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build . -t your-dockerhub-username/your-image-name:latest

    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/image
        tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    

    - name: Push Docker image
      run: docker push your-dockerhub-username/your-image-name:latest
