name: ImageSearchAPI Docker build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t image-search-api .
          docker tag image-search-api ${{ secrets.DOCKER_USERNAME }}/image-search-api
          docker push ${{ secrets.DOCKER_USERNAME }}/image-search-api
